### ISSUE TITLE
Import problems

### ISSUE THREAD

**Issue by LePhil** [excaliburjs/example-electron#3]
I can't seem to get proper imports to work, is there anything I'm doing wrong?
I added this in front of the game/index.js include in the index.html:
```
<script src="game/a.js"></script>
```

a.ts looks pretty simple:
```
export class Greeter {
    greeting: string;
    constructor(message: string) {
        this.greeting = message;
    }
    greet() {
        return "Hello, " + this.greeting;
    }
}
```

In the game/index.ts file I import the Greeter class and use it:
```
import {Greeter} from "./a";

let x = new Greeter("asd");
alert(x.greet());
```
Atom and `npm start` don't show any errors, but when electron is started it shows 2 errors in the dev console:
```
Uncaught ReferenceError: exports is not defined
    at a.ts:1
module.js:472 Uncaught Error: Cannot find module './a'
    at Module._resolveFilename (module.js:470)
    at Function.Module._resolveFilename (/my/path/structure/example-electron/node_modules/electron/dist/resources/electron.asar/common/reset-sea…:35)
    at Function.Module._load (module.js:418)
    at Module.require (module.js:498)
    at require (internal/module.js:20)
    at index.js:4
```

Any idea?

**Comment by alanag13** [comment]
This looks related to a problem that was fixed in https://github.com/excaliburjs/example-electron/pull/2. Are you using the typescript version that that PR set to be pinned?

**Comment by LePhil** [comment]
Yup, made no other changes to it than the ones mentioned. Still has `"typescript": "~2.1.4"` in the devDependencies.

**Comment by kamranayub** [comment]
If you want to use modules in Electron, you have to use them all the way down--so in **index.html** you have to change the script include to:

    <script>require('./game/index')</script>

And then it will work. See this [SO post](http://stackoverflow.com/questions/41418168/require-relative-path-in-client-side-js-in-electron).

Alternatively, you could use a bundler like Webpack to bundle your game and include the script file. It depends on how you want to develop.

I've updated the repo to reflect this as I think it'll be common for Electron devs. I also updated all the dependencies to the latest versions.

**Comment by LePhil** [comment]
Oh, I see. Well now I feel just silly, thanks for the hint. And thanks for Excalibur, slowly getting the hang of it :)

**Comment by kamranayub** [comment]
No problem! I didn't know that about electron either. Let us know if you
run into anymore issues!

**Comment by LePhil** [comment]
Hm, if you're offering already.. ;) I'm trying to get excalibur-tiled to work but I'm not sure how exactly to include it. TS won't let me use `import * as ex.Extensions from "../bower_components/excalibur-tiled/dist/excalibur-tiled";` which seemed like the obvious approach.

**Comment by kamranayub** [comment]
This would be a good question on the excalibur-tiled repository, do you
want to open an issue there? I have an answer, we just made a game using
the tiled plugin last month.
